version: "3.7"
services:
  mysql_local:
    image: mysql:5.7
    container_name: mysql_local
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - test_docker
networks:
  test_docker:
    external: true